In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
print("Libraries Imported Successfully")

Libraries Imported Successfully

In [12]:
import os
print(os.getcwd())
print(os.listdir())

C:\Users\Electronics Edge\OneDrive\Desktop\My Projects\Google-Play-Store-Analytics\notebooks
['.ipynb_checkpoints', '01_Data_cleaning.ipynb']

In [15]:
df = pd.read_csv("C:/Users/Electronics Edge/OneDrive/Desktop/My Projects/Google-Play-Store-Analytics/data/raw/googleplaystore.csv")

In [14]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [16]:
df.shape

(10841, 13)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [18]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [19]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(483)

In [21]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [22]:
df = df.drop_duplicates()
print("Duplicate records removed successfully")

Duplicate records removed successfully

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.isnull().sum()

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [25]:
df.dtypes

App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

In [26]:
df["Rating"] = df["Rating"].fillna(df["Rating"].median())

In [27]:
df["Rating"].isnull().sum()

np.int64(0)

In [28]:
df = df.dropna(subset=["Type"])

In [29]:
df["Type"].isnull().sum()

np.int64(0)

In [30]:
df = df.dropna(subset=["Content Rating"])

In [31]:
df["Content Rating"].isnull().sum()

np.int64(0)

In [32]:
df["Current Ver"] = df["Current Ver"].fillna("Unknown")

In [33]:
df["Current Ver"].isnull().sum()

np.int64(0)

In [34]:
df["Android Ver"] = df["Android Ver"].fillna("Unknown")

In [35]:
df["Android Ver"].isnull().sum()

np.int64(0)

In [36]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [37]:
df["Reviews"] = pd.to_numeric(df["Reviews"])

In [38]:
df["Reviews"].dtype

dtype('int64')

In [40]:
df["Installs"] = df["Installs"].str.replace(",","", regex=False)
df["Installs"] = df["Installs"].str.replace("+","", regex=False)

In [41]:
df["Installs"] = pd.to_numeric(df["Installs"])

In [42]:
df["Installs"].dtype

dtype('int64')

In [43]:
df["Price"] = df["Price"].str.replace("$","", regex=False)

In [44]:
df["Price"] = pd.to_numeric(df["Price"])

In [45]:
df["Price"].dtype

dtype('float64')

In [46]:
df["Size"].unique()

<StringArray>
[  '19M',   '14M',  '8.7M',   '25M',  '2.8M',  '5.6M',   '29M',   '33M',
  '3.1M',   '28M',
 ...
  '467k',  '157k',   '44k',  '676k',   '67k',  '552k',  '885k', '1020k',
  '582k',  '619k']
Length: 461, dtype: str

In [47]:
df["Size"] = df["Size"].replace("Varies with device",np.nan)

In [48]:
df["Size"] = df["Size"].str.replace("M","", regex=False)
df["Size"] = df["Size"].str.replace("k","", regex=False)

In [49]:
df["Size"] = pd.to_numeric(df["Size"],errors="coerce")

In [50]:
df["Size"] = df["Size"].fillna(df["Size"].median())

In [51]:
df.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size              float64
Installs            int64
Type                  str
Price             float64
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [16]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [17]:
df.to_csv("../data/cleaned/retail_sales_cleaned.csv", index=False)
print("Cleaned Dataset saved successfully")

Cleaned Dataset saved successfully

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv("C:/Users/Electronics Edge/OneDrive/Desktop/My Projects/Google-Play-Store-Analytics/data/raw/googleplaystore.csv")

In [5]:
df["Installs"].head(10)

0        10,000+
1       500,000+
2     5,000,000+
3    50,000,000+
4       100,000+
5        50,000+
6        50,000+
7     1,000,000+
8     1,000,000+
9        10,000+
Name: Installs, dtype: str

In [6]:
df["Installs"].describe()

count          10841
unique            22
top       1,000,000+
freq            1579
Name: Installs, dtype: object

In [7]:
df["Installs"].dtype

In [8]:
df["Installs"] = df["Installs"].str.replace(",","", regex=False)
df["Installs"] = df["Installs"].str.replace("+","", regex=False)

In [11]:
df["Installs"].unique()

<StringArray>
[     '10000',     '500000',    '5000000',   '50000000',     '100000',
      '50000',    '1000000',   '10000000',       '5000',  '100000000',
 '1000000000',       '1000',  '500000000',         '50',        '100',
        '500',         '10',          '1',          '5',          '0',
       'Free']
Length: 21, dtype: str

In [12]:
df["Installs"].value_counts()

Installs
1000000       1579
10000000      1252
100000        1169
10000         1054
1000           907
5000000        752
100            719
500000         539
50000          479
5000           477
100000000      409
10             386
500            330
50000000       289
50             205
5               82
500000000       72
1               67
1000000000      58
0               15
Free             1
Name: count, dtype: int64

In [13]:
df["Installs"] = df["Installs"].replace("Free", 0)

In [14]:
df["Installs"] = df["Installs"].astype(int)

In [15]:
df["Installs"].dtype

dtype('int64')